name=input("Enter your name:")
rollno=int(input("Enter your roll number:"))
marks1=int(input("Enter marks of subject 1:"))
marks2=int(input("Enter marks of subject 2:"))
marks3=int(input("Enter marks of subject 3:"))
marks4=int(input("Enter marks of subject 4:"))
marks5=int(input("Enter marks of subject 5:"))
total=marks1+marks2+marks3+marks4+marks5
print("Total Marks obtained by",name,"is:",total)
print("Average Marks obtained by",name,"is:",total/5)
print("Percentage obtained by",name,"is:",(total/500)*100)
